### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RojasMilo** [Computer-Programming-I-UIS/game-press-restart#1]
Alguna idea del error?

![image](https://user-images.githubusercontent.com/20142943/92528330-37dd9380-f1ee-11ea-8c54-f9eae459bcea.png)

**Comment by 2190431-Luis-Esteban-Castiblanco** [comment]
se debió a una mala definición del suelo profe, ya está corregido, parcialmente, hay que ajustar los parámetros para que encajen exactamente con el suelo
